# Generated by Django 2.1.7 on 2019-02-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sopx', models.IntegerField(default=0)),
                ('sopy', models.IntegerField(default=0)),
                ('r1px', models.IntegerField(default=0)),
                ('r1py', models.IntegerField(default=0)),
                ('r1pface', models.CharField(max_length=50)),
                ('inst1', models.CharField(max_length=50)),
                ('r2px', models.IntegerField(default=0)),
                ('r2py', models.IntegerField(default=0)),
                ('r2pface', models.CharField(max_length=50)),
                ('inst2', models.CharField(max_length=50)),
            ],
        ),
    ]
