# Generated by Django 2.1.7 on 2019-02-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MRInputs',
            new_name='MRInput',
        ),
    ]
